services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony:delegated
    networks:
      - symfony_network
    depends_on:
      - mariadb
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y libzip-dev libpq-dev &&
      docker-php-ext-install pdo pdo_mysql &&
      php-fpm
      "
  webserver:
    image: nginx:1.23
    container_name: symfony_webserver
    volumes:
      - .:/var/www/symfony:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "8080:80"
    networks:
      - symfony_network
    depends_on:
      - app

  mariadb:
    image: mariadb:10.11
    container_name: symfony_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  mariadb_data:
